// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModularMonolithERP.Infrastructure.DataAccess;

#nullable disable

namespace ModularMonolithERP.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241024102749_AñadirOrdenCarritoModel")]
    partial class AñadirOrdenCarritoModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ModularMonolithERP.Core.Entidades.OrdenCarritoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoSuministradorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoSuministradorId");

                    b.ToTable("OrdenesCarritos");
                });

            modelBuilder.Entity("ModularMonolithERP.Core.Entidades.ProductoSuministradorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CantidadProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("CosteProducto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DescripcionProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SuministradorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SuministradorId")
                        .IsUnique();

                    b.ToTable("ProductosSuministradores");
                });

            modelBuilder.Entity("ModularMonolithERP.Core.Entidades.SuministradorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoriaProveedor")
                        .HasColumnType("int");

                    b.Property<int>("CondicionesPagoEnum")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormasPago")
                        .HasColumnType("int");

                    b.Property<int>("MetodosTransporte")
                        .HasColumnType("int");

                    b.Property<int>("MonedaPreferida")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaisOrigen")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoContacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoProveedor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Suministradores");
                });

            modelBuilder.Entity("ModularMonolithERP.Core.Entidades.TransaccionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Concepto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaTransaccion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TipoGasto")
                        .HasColumnType("int");

                    b.Property<int?>("TipoIngreso")
                        .HasColumnType("int");

                    b.Property<int>("TipoTransaccion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("ModularMonolithERP.Core.Entidades.OrdenCarritoModel", b =>
                {
                    b.HasOne("ModularMonolithERP.Core.Entidades.ProductoSuministradorModel", "ProductoSuministrador")
                        .WithMany()
                        .HasForeignKey("ProductoSuministradorId");

                    b.Navigation("ProductoSuministrador");
                });

            modelBuilder.Entity("ModularMonolithERP.Core.Entidades.ProductoSuministradorModel", b =>
                {
                    b.HasOne("ModularMonolithERP.Core.Entidades.SuministradorModel", "Suministrador")
                        .WithOne("ProductoSuministrador")
                        .HasForeignKey("ModularMonolithERP.Core.Entidades.ProductoSuministradorModel", "SuministradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suministrador");
                });

            modelBuilder.Entity("ModularMonolithERP.Core.Entidades.SuministradorModel", b =>
                {
                    b.Navigation("ProductoSuministrador");
                });
#pragma warning restore 612, 618
        }
    }
}
